[project]
name = 'Customer-Service-Escalation-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.escalation-manager]
path = 'contracts/escalation-manager.clar'
clarity_version = 2
epoch = 2.5

[contracts.process-improvement]
path = 'contracts/process-improvement.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
